# 1)a

In [1]:
class Employee:
    employee_count = 0

    def __init__(self, name, designation):
        self.name = name
        self.designation = designation
        
        Employee.employee_count += 1


employee1 = Employee("Sachin Tiwari", "Software Engineer")
employee2 = Employee("John Duke", "Business Manager")


print(f"{employee1.name} is a {employee1.designation}")
print(f"{employee2.name} is a {employee2.designation}")

print(f"Total number of employees: {Employee.employee_count}")


Sachin Tiwari is a Software Engineer
John Duke is a Business Manager
Total number of employees: 2


# 1)b

In [2]:
class Employee:
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

employee1 = Employee("Sachin Tiwari", "Tiwari Family", 45000, "IT Department")
employee2 = Employee("John Duke", "Duke Family", 58000, "HR Department")


print(f"{employee1.name} works in the {employee1.department} and earns ${employee1.salary}")
print(f"{employee2.name} works in the {employee2.department} and earns ${employee2.salary}")
print(f"{employee1.name}'s family name is {employee1.family}")
print(f"{employee2.name}'s family name is {employee2.family}")

Sachin Tiwari works in the IT Department and earns $45000
John Duke works in the HR Department and earns $58000
Sachin Tiwari's family name is Tiwari Family
John Duke's family name is Duke Family


# 1)c

In [3]:
class Employee:
    
    all_employees = []

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
       
        Employee.all_employees.append(self)

    @classmethod
    def average_salary(cls):
       
        total_salary = sum(employee.salary for employee in cls.all_employees)
        average_salary = total_salary / len(cls.all_employees) if len(cls.all_employees) > 0 else 0
        return average_salary


employee1 = Employee("Sachin Tiwari", "Tiwari Family", 45000, "IT Department")
employee2 = Employee("Navya Sharma", "Sharma Family", 60000, "Finance Department")
employee3 = Employee("John Duke", "Duke Family", 58000, "HR Department")




average_salary = Employee.average_salary()
print(f"Average salary of all employees: ${average_salary:.2f}")

Average salary of all employees: $54333.33


# 1)d

In [4]:
class Employee:
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, working_hours):
      
        super().__init__(name, family, salary, department)
        self.working_hours = working_hours


fulltime_employee = FulltimeEmployee("Sachin Tiwari", "Tiwari Family", 45000, "IT Department", 46)


print(f"{fulltime_employee.name} works {fulltime_employee.working_hours} hours per week in the {fulltime_employee.department} department.")
print(f"{fulltime_employee.name}'s salary is ${fulltime_employee.salary}")

Sachin Tiwari works 46 hours per week in the IT Department department.
Sachin Tiwari's salary is $45000


# 1)e

In [5]:
class Employee:
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

    def display_info(self):
        print(f"Employee: {self.name}, Department: {self.department}, Salary: ${self.salary}")

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, working_hours):
        super().__init__(name, family, salary, department)
        self.working_hours = working_hours

    def display_info(self):
        super().display_info()
        print(f"Working Hours: {self.working_hours} hours per week")


employee = Employee("Sachin Tiwari", "Tiwari Family", 45000, "IT Department")
fulltime_employee = FulltimeEmployee("Navya Sharma", "Sharma Family", 60000, "Finance Department", 46)


print("Employee Information:")
employee.display_info()

print("\nFulltime Employee Information:")
fulltime_employee.display_info()

Employee Information:
Employee: Sachin Tiwari, Department: IT Department, Salary: $45000

Fulltime Employee Information:
Employee: Navya Sharma, Department: Finance Department, Salary: $60000
Working Hours: 46 hours per week


# 2)

In [6]:
import numpy as np

random_vector = np.random.uniform(1, 20, 20)
random_vector


array([15.90956965, 10.97998826, 10.59139136,  7.50455076,  6.38808372,
        9.35254733, 14.67248002,  2.51976654,  8.35476149,  7.96582503,
       13.58085584, 11.92769847,  1.77773618, 11.73036626,  2.86917727,
       18.64194389,  2.1765193 ,  7.46182031, 19.26295139,  3.66761856])

In [7]:
reshaped_array = random_vector.reshape(4, 5)
reshaped_array

array([[15.90956965, 10.97998826, 10.59139136,  7.50455076,  6.38808372],
       [ 9.35254733, 14.67248002,  2.51976654,  8.35476149,  7.96582503],
       [13.58085584, 11.92769847,  1.77773618, 11.73036626,  2.86917727],
       [18.64194389,  2.1765193 ,  7.46182031, 19.26295139,  3.66761856]])

In [8]:
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0
reshaped_array

array([[ 0.        , 10.97998826, 10.59139136,  7.50455076,  6.38808372],
       [ 9.35254733,  0.        ,  2.51976654,  8.35476149,  7.96582503],
       [ 0.        , 11.92769847,  1.77773618, 11.73036626,  2.86917727],
       [18.64194389,  2.1765193 ,  7.46182031,  0.        ,  3.66761856]])